export * from './validators/required.directive';
export * from './validators/max.directive'
export * from './validators/required.directive';
export * from './validators/ng-model-validator.directive';
export * from './validators/country-code.directive';
export * from './validators/currency-code.directive';
export * from './validators/email.directive';
export * from './validators/email-many.directive';
export * from './validators/id-card.directive';
export * from './validators/min.directive';
export * from './validators/max.directive';
export * from './validators/minlength.directive';
export * from './validators/maxlength.directive'
